{% set name = "r-catboost" %}
{% set version = "0.12.1.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Linux-{{ version }}.tgz  # [linux]
  sha256: 9c3d3edfc7e2076b25f9b7d45f5536eae59235d84304813eba21b5555d70d514  # [linux]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Windows-{{ version }}.tgz  # [win]
  sha256: 14bbf8c5051f1c76bbab89a4783a4f595bf7d374d8392bc4d2ed7cc17f1c2d3a  # [win]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Darwin-{{ version }}.tgz  # [osx]
  sha256: 4bdc6edf722ba675454bf7674da6ae6f5bfe1d2bd073795424ecc3ff214b33ab  # [osx]

build:
  number: 1000

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-jsonlite

  run:
    - r-base
    - r-jsonlite

test:
 commands:
    - $R -e "library('catboost')"  # [not win]
    - "\"%R%\" -e \"library('catboost')\""  # [win].

about:
  home: https://github.com/catboost/catboost
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'CatBoost is a machine learning algorithm that uses gradient boosting on decision trees. It is available as an open source library.'
  doc_url: https://tech.yandex.com/catboost/doc/dg/concepts/about-docpage/

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - curious-odd-man
    - dbast
