# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cE4YmjZs/8J2eRGCWSF0LBvTA8i3Ba5wYpWxrhRbMxzViHps77zWNMabJuMOtl93gswMafGjouf7fgtf6d8b+yJ/so+zJeGxqEiz+wUb12aLNHowyoPmTwwAzJ4AroTGigopbmKDeclYMwnKoE6UfydKndF4ZtgdcNQVDmdVEowh9GkcYeNNkjZBx69rpTeMDhNAvWYONngVz3fXTiPtoVDScIyNZXw+3t7RDSvdeGpMVpcQkqVGPT0/zph88wQ/cCmM81nmQ3ogh249S9CC1T6Dve2XDY/LotQNN9VmIekDwuGcZk2xN2JdbAyuJkdCGsPwwzNIBNcfktMcRDLRWgUOe6oAGEng1daCsrfrBj6Eb9Ko52xS6NMqArq2+GNGGQ7IoTc+AGs/OhgW325WRWpA7FbT694fVgFToZR2t5aqg9kJzCCJtJCQCE2Qoq8aLHsoEvowDc55x59QXw02oKBVNMUz8f61ZNT3CXaHZLuPGvlXRWxOVsJ5eXNF5QzOQWnlxcyOvyQl+5tgyfz6G9F1Z3N0YsiD8oddtQpMUQ9UAezTmA2xDDmyh4AU5NzwFNKFia/3SjcI7Fe5Z9XgX8t1jcQWf4u5lA0gsGW8Jy5Y1mUpU0Ln2zWDvJbIBfK0X//zm6UiA2LTlI614688s3Dd9WDh+ZU868Fcogky9j4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
