appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kOHqdMaOeYXPtSBecQInSkne0YWsjw6xmiC9dXLT1ONmWkbiQ0+bkjBVwhrZ8cZAr9JzwDFRuqBctM3M8hEKbwVKDQeGdc70/ZFfeV2ymJcKxZaJ50p3UZD/jOTOhH1LOQ1/LAOnA8hlu1o6GirtZxwE66v1YN7+9TrDSMR5Cp6oyZDf4O3Kx2bDZoxUW/XH4NE/Fbb0ilX3xnQC/hiIvIGMya6DdLAmgpKEDzL6+xaab3wT8ALI90wcVCg5XbHR5HlvNNRDNp5W8MuyUpNMjhT8TliIzdXc64V6MCz1kQ9ZNCwMQ6Gy14X56yepbUc0/SzaYsvAnXrqV2NbplCcRvG18bPw/narAAvFsRQc0jToU89sYW2oub5K4cqlpzOSPgwQ8xevXYc72BPAvx+jvQMr9qffIwm87GNKwilZ+wvRjlwZMK4V+4PYfNEMdN+tvb9T3DX9zeLPObeYwFa9Oz9+T0S01Lh/LDA1Kibppaa5Vogh3vUpWW+HouAxLtS8q2p/2MnPmG/ou8ai7ABltOhPkuHtN5AZCXPvjKhdBdhsNHn2IGCWF+JE4JAJq9kqDKyxQ7LCugyFS7kGtSIXT/T4SBh6rnWbTqIjL/4s5oAjzgD5neGdPbEYxyzIjxGi893oFsyw6w2W+Kd6qkTnnmPFll8T7e2YJEckZIWq4uA=}
