travis:
  secure:
    BINSTAR_TOKEN: cE4YmjZs/8J2eRGCWSF0LBvTA8i3Ba5wYpWxrhRbMxzViHps77zWNMabJuMOtl93gswMafGjouf7fgtf6d8b+yJ/so+zJeGxqEiz+wUb12aLNHowyoPmTwwAzJ4AroTGigopbmKDeclYMwnKoE6UfydKndF4ZtgdcNQVDmdVEowh9GkcYeNNkjZBx69rpTeMDhNAvWYONngVz3fXTiPtoVDScIyNZXw+3t7RDSvdeGpMVpcQkqVGPT0/zph88wQ/cCmM81nmQ3ogh249S9CC1T6Dve2XDY/LotQNN9VmIekDwuGcZk2xN2JdbAyuJkdCGsPwwzNIBNcfktMcRDLRWgUOe6oAGEng1daCsrfrBj6Eb9Ko52xS6NMqArq2+GNGGQ7IoTc+AGs/OhgW325WRWpA7FbT694fVgFToZR2t5aqg9kJzCCJtJCQCE2Qoq8aLHsoEvowDc55x59QXw02oKBVNMUz8f61ZNT3CXaHZLuPGvlXRWxOVsJ5eXNF5QzOQWnlxcyOvyQl+5tgyfz6G9F1Z3N0YsiD8oddtQpMUQ9UAezTmA2xDDmyh4AU5NzwFNKFia/3SjcI7Fe5Z9XgX8t1jcQWf4u5lA0gsGW8Jy5Y1mUpU0Ln2zWDvJbIBfK0X//zm6UiA2LTlI614688s3Dd9WDh+ZU868Fcogky9j4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
